enum ZoomLevel {
  MIN_ZOOM = 2,
  MAX_ZOOM = 20,
  DEFAULT_ZOOM = 14,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_10 = 20,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_9 = 18,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_8 = 16,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_7 = 14,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_6 = 12,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_5 = 10,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_4 = 8,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_3 = 4,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_2 = 3,
  MIN_GRID_ZOOM_GEOHASH_LENGTH_1 = 2,
}

export default ZoomLevel;
