export type ImdfFeatureType =
  | "venue"
  | "building"
  | "footprint"
  | "level"
  | "unit"
  | "fixture"
  | "section"
  | "geofence"
  | "kiosk"
  | "detail"
  | "opening"
  | "amenity"
  | "anchor"
  | "occupant"
  | "address"
  | "relationship";
