import { LayerSpecification } from "maplibre-gl";
import ZoomLevel from "../../map/models/ZoomLevel";
import { HerePoiIconName } from "./models/HerePoiIconName";

const HERE_VECTOR_TILES_SOURCE = "omv";
const HERE_POIS_SOURCE_LAYER = "pois";

export const HERE_POIS_LAYERS: LayerSpecification[] = [
  {
    id: "HereMapsPoisAirport",
    source: HERE_VECTOR_TILES_SOURCE,
    "source-layer": HERE_POIS_SOURCE_LAYER,
    filter: ["all", ["==", "kind", "airport"]],
    type: "symbol",
    layout: {
      "symbol-placement": "point",
      "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
      visibility: "visible",
      "icon-image": HerePoiIconName.HERE_POI_AIRPORT_ICON,
      "icon-size": 0.4,
      "icon-offset": [0, -40],
      "text-optional": true,
      "text-font": ["Fira GO Regular"],
      "text-size": 13,
      "text-anchor": "bottom",
      "text-offset": [0, -3.2],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "#000000",
      "text-halo-width": 0,
    },
    minzoom: ZoomLevel.MIN_GRID_ZOOM_GEOHASH_LENGTH_7,
  },
  {
    id: "HereMapsPoisArt",
    source: HERE_VECTOR_TILES_SOURCE,
    "source-layer": HERE_POIS_SOURCE_LAYER,
    filter: ["all", ["in", "kind", "artwork", "arts_centre"]],
    type: "symbol",
    layout: {
      "symbol-placement": "point",
      "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
      visibility: "visible",
      "icon-image": HerePoiIconName.HERE_POI_CINEMA_ICON,
      "icon-size": 0.4,
      "icon-offset": [0, -40],
      "text-optional": true,
      "text-font": ["Fira GO Regular"],
      "text-size": 13,
      "text-anchor": "bottom",
      "text-offset": [0, -3.2],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "#000000",
      "text-halo-width": 0,
    },
    minzoom: ZoomLevel.MIN_GRID_ZOOM_GEOHASH_LENGTH_7,
  },
  {
    id: "HereMapsPoisAttraction",
    source: HERE_VECTOR_TILES_SOURCE,
    "source-layer": HERE_POIS_SOURCE_LAYER,
    filter: ["all", ["==", "kind", "attraction"]],
    type: "symbol",
    layout: {
      "symbol-placement": "point",
      "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
      visibility: "visible",
      "icon-image": HerePoiIconName.HERE_POI_SIGHTS_ICON,
      "icon-size": 0.4,
      "icon-offset": [0, -40],
      "text-optional": true,
      "text-font": ["Fira GO Regular"],
      "text-size": 13,
      "text-anchor": "bottom",
      "text-offset": [0, -3.2],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "#000000",
      "text-halo-width": 0,
    },
    minzoom: ZoomLevel.MIN_GRID_ZOOM_GEOHASH_LENGTH_7,
  },
  {
    id: "HereMapsPoisBeach",
    source: HERE_VECTOR_TILES_SOURCE,
    "source-layer": HERE_POIS_SOURCE_LAYER,
    filter: ["all", ["==", "kind", "beach"]],
    type: "symbol",
    layout: {
      "symbol-placement": "point",
      "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
      visibility: "visible",
      "icon-image": HerePoiIconName.HERE_POI_BEACH_ICON,
      "icon-size": 0.4,
      "icon-offset": [0, -40],
      "text-optional": true,
      "text-font": ["Fira GO Regular"],
      "text-size": 13,
      "text-anchor": "bottom",
      "text-offset": [0, -3.2],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "#000000",
      "text-halo-width": 0,
    },
    minzoom: ZoomLevel.MIN_GRID_ZOOM_GEOHASH_LENGTH_7,
  },
  {
    id: "HereMapsPoisMuseum",
    source: HERE_VECTOR_TILES_SOURCE,
    "source-layer": HERE_POIS_SOURCE_LAYER,
    filter: ["all", ["==", "kind", "museum"]],
    type: "symbol",
    layout: {
      "symbol-placement": "point",
      "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
      visibility: "visible",
      "icon-image": HerePoiIconName.HERE_POI_MUSEUM_ICON,
      "icon-size": 0.4,
      "icon-offset": [0, -40],
      "text-optional": true,
      "text-font": ["Fira GO Regular"],
      "text-size": 13,
      "text-anchor": "bottom",
      "text-offset": [0, -3.2],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "#000000",
      "text-halo-width": 0,
    },
    minzoom: ZoomLevel.MIN_GRID_ZOOM_GEOHASH_LENGTH_7,
  },
  {
    id: "HereMapsPoisHospital",
    source: HERE_VECTOR_TILES_SOURCE,
    "source-layer": HERE_POIS_SOURCE_LAYER,
    filter: ["all", ["==", "kind", "hospital"]],
    type: "symbol",
    layout: {
      "symbol-placement": "point",
      "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
      visibility: "visible",
      "icon-image": HerePoiIconName.HERE_POI_HOSPITAL_ICON,
      "icon-size": 0.4,
      "icon-offset": [0, -40],
      "text-optional": true,
      "text-font": ["Fira GO Regular"],
      "text-size": 13,
      "text-anchor": "bottom",
      "text-offset": [0, -3.2],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "#000000",
      "text-halo-width": 0,
    },
    minzoom: ZoomLevel.MIN_GRID_ZOOM_GEOHASH_LENGTH_7,
  },
  {
    id: "HereMapsPoisStation",
    source: HERE_VECTOR_TILES_SOURCE,
    "source-layer": HERE_POIS_SOURCE_LAYER,
    filter: ["all", ["==", "kind", "station"]],
    type: "symbol",
    layout: {
      "symbol-placement": "point",
      "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
      visibility: "visible",
      "icon-image": HerePoiIconName.HERE_POI_STATION_ICON,
      "icon-size": 0.4,
      "icon-offset": [0, -40],
      "text-optional": true,
      "text-font": ["Fira GO Regular"],
      "text-size": 13,
      "text-anchor": "bottom",
      "text-offset": [0, -3.2],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "#000000",
      "text-halo-width": 0,
    },
    minzoom: ZoomLevel.MIN_GRID_ZOOM_GEOHASH_LENGTH_7,
  },
  {
    id: "PoiLabel",
    source: HERE_VECTOR_TILES_SOURCE,
    "source-layer": HERE_POIS_SOURCE_LAYER,
    filter: [
      "all",
      [
        "in",
        "kind",
        "border_crossing",
        "ferry_terminal",
        "golf_course",
        "hamlet",
        "historical",
        "motorway_junction",
        "named_place",
        "neighborhood",
        "peak",
        "sports_centre",
        "taxi",
        "theme_park",
      ],
    ],
    type: "symbol",
    layout: {
      "symbol-placement": "point",
      "text-field": ["coalesce", ["get", "name:en"], ["get", "name"]],
      visibility: "visible",
      "icon-image": HerePoiIconName.HERE_POI_DEFAULT_ICON,
      "icon-size": 0.4,
      "icon-offset": [0, -40],
      "text-optional": true,
      "text-font": ["Fira GO Regular"],
      "text-size": 13,
      "text-anchor": "bottom",
      "text-offset": [0, -3.2],
    },
    paint: {
      "text-color": "#000000",
      "text-halo-color": "#000000",
      "text-halo-width": 0,
    },
    minzoom: ZoomLevel.MIN_GRID_ZOOM_GEOHASH_LENGTH_7,
  },
];
